
-- =============================================================================
-- RAG Chatbot — Postgres Schema (Dynamic Data Store)
-- =============================================================================
-- Holds live availability, operating hours, and chatbot-collected reservations.
-- =============================================================================


CREATE SCHEMA IF NOT EXISTS parking;
SET search_path TO parking;


-- Enums -----------------------------------------------------------------------
CREATE TYPE reservation_status AS ENUM ('pending', 'confirmed', 'cancelled', 'expired');


-- =============================================================================
-- spaces — individual parking spaces (live availability)
-- =============================================================================
CREATE TABLE spaces (
    id              SERIAL PRIMARY KEY,
    floor           SMALLINT NOT NULL,
    space_number    VARCHAR(20) NOT NULL,
    is_available    BOOLEAN  NOT NULL DEFAULT TRUE,
    last_updated    TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_spaces_location UNIQUE (floor, space_number)
);

CREATE INDEX idx_spaces_floor       ON spaces (floor);
CREATE INDEX idx_spaces_available   ON spaces (is_available) WHERE is_available = TRUE;


-- =============================================================================
-- operating_hours — open/close times per day, with holiday overrides
-- =============================================================================
-- day_of_week: 0 = Sunday … 6 = Saturday   (validated in Python)
-- For weekly recurring hours, leave specific_date NULL.
-- For date-specific overrides, set specific_date.
-- =============================================================================
CREATE TABLE operating_hours (
    id              SERIAL PRIMARY KEY,
    day_of_week     SMALLINT,
    specific_date   DATE,
    open_time       TIME NOT NULL,
    close_time      TIME NOT NULL,
    is_holiday      BOOLEAN NOT NULL DEFAULT FALSE,
    is_closed       BOOLEAN NOT NULL DEFAULT FALSE,
    note            TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Partial unique indexes prevent duplicate weekly rows / duplicate date overrides.
CREATE UNIQUE INDEX uq_operating_hours_weekly
    ON operating_hours (day_of_week)
    WHERE specific_date IS NULL AND is_holiday = FALSE;

CREATE UNIQUE INDEX uq_operating_hours_date
    ON operating_hours (specific_date)
    WHERE specific_date IS NOT NULL;


-- =============================================================================
-- reservations — bookings collected by the reservation agent
-- =============================================================================
-- id is a UUID generated by the application (e.g. Python's uuid.uuid4()).
-- =============================================================================
CREATE TABLE reservations (
    id                  UUID PRIMARY KEY,
    user_session_id     VARCHAR(128) NOT NULL,
    space_id            INTEGER NOT NULL REFERENCES spaces(id) ON DELETE RESTRICT,
    start_time          TIMESTAMPTZ NOT NULL,
    end_time            TIMESTAMPTZ NOT NULL,
    vehicle_plate       VARCHAR(20)  NOT NULL,
    contact_email       VARCHAR(255) NOT NULL,
    status              reservation_status NOT NULL DEFAULT 'pending',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_reservations_session    ON reservations (user_session_id);
CREATE INDEX idx_reservations_space_time ON reservations (space_id, start_time, end_time);
CREATE INDEX idx_reservations_status     ON reservations (status, created_at DESC);
CREATE INDEX idx_reservations_email      ON reservations (contact_email);